import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';
import { requireFeature } from '@/lib/api-auth';
import { validateBody, z } from '@/lib/validate';
import { generateEstimatePdf } from '@/lib/estimate-pdf-server';
import { sendEmailDetailed, buildNotificationEmail } from '@/lib/resend';
import { getEmailSignature } from '@/lib/email-signature';
import { estimatePdfFilename } from '@/lib/estimate-pdf';
import { deepLinks } from '@/lib/deep-links';
import { loadEstimateAttachmentRows, fetchEstimateAttachments } from '@/lib/estimate-attachments';
import { MAX_ATTACHMENT_BYTES } from '@/lib/email-attachments';

export const dynamic = 'force-dynamic';
export const maxDuration = 60;

const Schema = z.object({
  emails: z.array(z.string().email()).max(20).optional(),
  bccSelf: z.boolean().optional(),
  message: z.string().max(4000).optional(),
  // Files the rep picked off the estimate (estimate_files) to ride along
  // with the PDF — pictures, spec sheets.
  attachmentFileIds: z.array(z.string().uuid()).max(20).optional(),
  preview: z.boolean().optional(),
});

function getSupabase() {
  return createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!
  );
}

/**
 * POST /api/estimates/[id]/email-pdf — email the FleetSuite enhanced-
 * estimate PDF to the customer, through the standard compose contract
 * (docs/customer-email-standard.md): emails[] / bccSelf / message /
 * preview. Preview renders the exact email (signature included) with zero
 * side effects; the real send attaches the PDF generated by the same
 * renderer as GET /api/estimates/[id]/pdf, plus any estimate files the rep
 * picked, and Reply-To's the sender.
 */
export async function POST(req: NextRequest, { params }: { params: { id: string } }) {
  const auth = await requireFeature(req, 'estimates');
  if (auth.error) return auth.error;

  const parsed = await validateBody(req, Schema);
  if (parsed.error) return parsed.error;
  const body = parsed.data;

  const supabase = getSupabase();

  const { data: estimate, error: estErr } = await supabase
    .from('estimates')
    .select('id, estimate_number, title, customer_id, customer_name, customer_netsuite_id, grand_total')
    .eq('id', params.id)
    .single();
  if (estErr || !estimate) {
    return NextResponse.json({ error: 'Estimate not found' }, { status: 404 });
  }

  // Default recipient: primary external contact, then the synced customer
  // email — the same fallback order as send-for-approval.
  const composeEmails = (body.emails || []).map(e => e.trim()).filter(Boolean);
  let defaultEmail: string | null = null;
  if (composeEmails.length === 0 && estimate.customer_id) {
    const { data: primary } = await supabase
      .from('external_contacts')
      .select('email')
      .eq('customer_id', estimate.customer_id)
      .eq('is_primary', true)
      .maybeSingle();
    defaultEmail = primary?.email || null;
    if (!defaultEmail) {
      const { data: customer } = await supabase
        .from('customers')
        .select('email')
        .eq('id', estimate.customer_id)
        .maybeSingle();
      defaultEmail = customer?.email || null;
    }
  }
  const emailList = composeEmails.length > 0 ? composeEmails : (defaultEmail ? [defaultEmail] : []);

  const { data: settings } = await supabase
    .from('wrap_quote_settings')
    .select('company')
    .eq('id', 1)
    .maybeSingle();
  const companyName = settings?.company?.name || 'BMG Fleet';

  // Picked estimate files ride along with the PDF. Resolved before the
  // preview so it can name them, and validated against THIS estimate.
  const picked = await loadEstimateAttachmentRows(supabase, params.id, body.attachmentFileIds);
  if (!picked.ok) return NextResponse.json({ error: picked.error }, { status: picked.status });

  const filename = estimatePdfFilename(estimate);
  const subject = `[BMG Fleet] Estimate #${estimate.estimate_number}${estimate.title ? ` — ${estimate.title}` : ''}`;
  const total = Number(estimate.grand_total || 0);
  const bodyText = `Attached is Estimate #${estimate.estimate_number}`
    + `${estimate.title ? ` (${estimate.title})` : ''} from ${companyName}`
    + `${estimate.customer_name ? ` for ${estimate.customer_name}` : ''}`
    + `${total > 0 ? ` — total $${total.toFixed(2)}` : ''}.`;
  const signature = await getEmailSignature(supabase, auth.user?.id);
  const html = buildNotificationEmail(
    `Estimate #${estimate.estimate_number}`,
    bodyText,
    undefined,
    undefined,
    {
      note: body.message?.trim() || undefined,
      attachmentNames: [filename, ...picked.rows.map(r => r.file_name)],
      signature,
    },
  );

  // Preview: the exact email that would go out — nothing generated or sent.
  if (body.preview) {
    return NextResponse.json({ preview: true, to: emailList.join(', ') || null, subject, html });
  }

  if (emailList.length === 0) {
    return NextResponse.json({ error: 'No email on file for this customer. Add a recipient first.' }, { status: 400 });
  }

  const pdf = await generateEstimatePdf(supabase, params.id);
  if (!pdf.ok) {
    return NextResponse.json({ error: pdf.error }, { status: pdf.status });
  }

  // The estimate PDF takes its share of the budget first — the picked files
  // get what's left. A file that can't be fetched fails the send with its
  // name, rather than going out quietly missing.
  const extras = await fetchEstimateAttachments(
    picked.rows,
    Math.max(0, MAX_ATTACHMENT_BYTES - pdf.buffer.byteLength),
  );
  if (!extras.ok) return NextResponse.json({ error: extras.error }, { status: extras.status });

  const senderEmail = auth.user?.email || undefined;
  const { ok, id: resendId } = await sendEmailDetailed(
    emailList,
    subject,
    html,
    undefined,
    [
      { filename: pdf.filename, content: pdf.buffer, contentType: 'application/pdf' },
      ...extras.attachments,
    ],
    senderEmail,
    body.bccSelf && senderEmail ? [senderEmail] : undefined,
    {
      kind: 'estimate_pdf',
      sentBy: auth.user?.id,
      contextUrl: deepLinks.estimate(estimate.id),
      customerId: estimate.customer_id,
      netsuiteCustomerId: estimate.customer_netsuite_id,
    },
  );

  if (!ok) {
    return NextResponse.json({ error: 'Email failed to send — check Resend configuration and try again.' }, { status: 502 });
  }

  return NextResponse.json({
    success: true,
    resendId,
    dispatch: {
      email: {
        ok: true,
        target: emailList.join(', '),
        bcc: body.bccSelf && senderEmail ? senderEmail : null,
      },
    },
  });
}
