-- Migration 194: dated, sequential job numbers (K4)
--
-- The meeting: "job numbers generated by the system are currently cryptic
-- and need a shorter, meaningful format." Six independent generators made
-- base36-timestamp soup (GFX-MSG7L76U) or random suffixes with collision
-- retries (EST-2608-K3QX). One atomic per-prefix, per-month sequence
-- replaces them all: EST-2608-041, GFX-2608-017, WQ-2608-003, and the
-- graphics category prefixes (PRF/INT/CSG). Existing records keep their
-- old numbers (meeting Q4: confirmed).
--
-- Modeled on CNI's generate_cni_job_number but table-backed and race-safe:
-- the ON CONFLICT upsert increments under row lock, so two simultaneous
-- creates get consecutive numbers instead of a collision retry (retires
-- roadmap B14 properly).
--
-- SECURITY DEFINER: wrap-quote, schedule, and graphics numbers are minted
-- client-side, so authenticated users need EXECUTE; the sequence table
-- itself stays locked down (RLS on, no policies — only the function
-- touches it).

CREATE TABLE IF NOT EXISTS job_number_sequences (
  prefix TEXT NOT NULL,
  period TEXT NOT NULL,           -- YYMM
  last_seq INT NOT NULL DEFAULT 0,
  PRIMARY KEY (prefix, period)
);

ALTER TABLE job_number_sequences ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.next_job_number(p_prefix TEXT)
RETURNS TEXT AS $$
DECLARE
  v_prefix TEXT := upper(trim(p_prefix));
  v_period TEXT := to_char(now(), 'YYMM');
  v_seq INT;
BEGIN
  IF v_prefix !~ '^[A-Z]{2,4}$' THEN
    RAISE EXCEPTION 'invalid job number prefix: %', p_prefix;
  END IF;
  INSERT INTO public.job_number_sequences AS s (prefix, period, last_seq)
  VALUES (v_prefix, v_period, 1)
  ON CONFLICT (prefix, period)
  DO UPDATE SET last_seq = s.last_seq + 1
  RETURNING last_seq INTO v_seq;
  -- lpad() TRUNCATES beyond the target length — greatest() lets the rare
  -- 1000th-in-a-month number widen to 4 digits instead of corrupting.
  RETURN v_prefix || '-' || v_period || '-'
      || lpad(v_seq::TEXT, greatest(3, length(v_seq::TEXT)), '0');
END;
$$ LANGUAGE plpgsql SECURITY DEFINER
SET search_path = '';

GRANT EXECUTE ON FUNCTION public.next_job_number(TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.next_job_number(TEXT) TO service_role;
