-- Wrap quote estimator: search and filter the vehicle template library in
-- the database instead of in the browser.
--
-- The Art Station import (2026-10-02) took the library from ~250 templates
-- to ~9,450, and the wrap quotes page was downloading every row (10 pages of
-- 1,000, one after another) before it was usable. The page now asks these
-- functions for just what it shows: the filter dropdown choices, the search
-- matches, a page of the Templates grid.
--
-- Roof / bed / cab / body / wheelbase used to be read out of each template's
-- description in the browser (src/lib/template-facets.ts). They're stored
-- columns now, generated by vehicle_template_facets() below, so every insert
-- path (Add Template, bulk upload, the Art Station import script) fills them
-- with no app code involved, and adding the columns backfills existing rows.
-- vehicle_template_facets() is a port of templateFacets() — change both
-- together; src/lib/template-facets-sql.test.ts runs the two side by side.
--
-- Idempotent: CREATE OR REPLACE / IF NOT EXISTS throughout.

CREATE OR REPLACE FUNCTION public.vehicle_template_facets(p_variant TEXT, p_name TEXT, p_wheelbase_in NUMERIC)
RETURNS JSONB
LANGUAGE plpgsql
IMMUTABLE
AS $$
DECLARE
  txt TEXT;
  inches TEXT := '';
  extended BOOLEAN;
  m TEXT[];
  bed TEXT := '';
  w TEXT;
BEGIN
  -- The variant, else the name when there is no variant.
  txt := CASE WHEN COALESCE(p_variant, '') <> '' THEN p_variant ELSE COALESCE(p_name, '') END;
  txt := regexp_replace(txt, '^\s+|\s+$', '', 'g');

  -- Wheelbase: the column (whole inches), else an "NNNin" token in the text.
  IF COALESCE(p_wheelbase_in, 0) > 0 THEN
    inches := round(p_wheelbase_in)::BIGINT::TEXT;
  ELSE
    m := regexp_match(txt, '(?:^|[\s,;])(\d{2,3})in\y');
    IF m IS NOT NULL THEN inches := m[1]; END IF;
  END IF;
  -- "Extended" / "Extended Body", but not a pickup's "Extended Cab".
  extended := txt ~* '\yextended\y(?! cab)';

  -- Bed: a measured bed/box wins over a word.
  m := regexp_match(txt, '(\d+(?:\.\d+)?)\s*(?:''|ft)\s*(?:standard |long |short )?(?:box|bed)\y', 'i');
  IF m IS NOT NULL THEN
    bed := m[1] || '''';
  ELSE
    m := regexp_match(txt, '(\d+)''(\d+)in\s*(?:box|bed)\y', 'i');
    IF m IS NOT NULL THEN
      bed := m[1] || '''' || m[2] || '"';
    ELSE
      m := regexp_match(txt, '\y(\d+(?:\.\d+)?) (?:box|bed)\y', 'i');
      IF m IS NOT NULL THEN
        bed := m[1] || '''';
      ELSIF txt ~* '\yflat ?bed\y' THEN
        bed := 'Flat Bed';
      ELSIF txt ~* '\yflareside\y' THEN
        bed := 'Flareside';
      ELSE
        m := regexp_match(txt, '\y(short|standard|regular|reg|long)\s?(?:box|bed)\y', 'i');
        IF m IS NOT NULL THEN
          w := lower(m[1]);
          bed := CASE WHEN w = 'short' THEN 'Short' WHEN w = 'long' THEN 'Long' ELSE 'Standard' END;
        ELSIF txt ~* '\ycab chassis\y|\ychassis\y' AND txt ~* '\ycab\y' AND txt !~* '\ychassis cab\y' THEN
          bed := 'Chassis';
        END IF;
      END IF;
    END IF;
  END IF;

  RETURN jsonb_build_object(
    'wheelbase', CASE WHEN inches <> '' AND extended THEN inches || ' Extended' ELSE inches END,
    -- First hit wins, in the same order as BODIES / ROOFS / CABS.
    'body', CASE
      WHEN txt ~* '\ychassis cab\y' THEN 'Chassis Cab'
      WHEN txt ~* '\ycutaway\y' THEN 'Cutaway'
      WHEN txt ~* '\ycrew van\y' THEN 'Crew Van'
      WHEN txt ~* '\ycargo\y' THEN 'Cargo'
      WHEN txt ~* '\ypassenger\y' THEN 'Passenger'
      WHEN txt ~* '\ywagon\y' THEN 'Wagon'
      WHEN txt ~* '\ysedan\y' THEN 'Sedan'
      WHEN txt ~* '\ycoupe\y' THEN 'Coupe'
      WHEN txt ~* '\yhatchback\y' THEN 'Hatchback'
      WHEN txt ~* '\y(?:convertible|cabriolet|roadster)\y' THEN 'Convertible'
      ELSE '' END,
    'roof', CASE
      WHEN txt ~* '\ysuper high roof\y' THEN 'Super High'
      WHEN txt ~* '\ymega roof\y' THEN 'Mega'
      WHEN txt ~* '\yhigh roof\y' THEN 'High'
      WHEN txt ~* '\ymed(?:ium)?\.? roof\y' THEN 'Medium'
      WHEN txt ~* '\ylow roof\y' THEN 'Low'
      WHEN txt ~* '\y(?:standard|regular) roof\y' THEN 'Standard'
      ELSE '' END,
    'bed', bed,
    'cab', CASE
      WHEN txt ~* '\ysuper ?crew\y' THEN 'SuperCrew'
      WHEN txt ~* '\ycrew ?max\y' THEN 'CrewMax'
      WHEN txt ~* '\ysuper ?cab\y' THEN 'Super Cab'
      WHEN txt ~* '\ycrew ?cab\y' THEN 'Crew Cab'
      WHEN txt ~* '\yextended cab\y' THEN 'Extended Cab'
      WHEN txt ~* '\ydouble cab\y' THEN 'Double Cab'
      WHEN txt ~* '\yquad cab\y' THEN 'Quad Cab'
      WHEN txt ~* '\ymega cab\y' THEN 'Mega Cab'
      WHEN txt ~* '\yking cab\y' THEN 'King Cab'
      WHEN txt ~* '\yaccess cab\y' THEN 'Access Cab'
      WHEN txt ~* '\yclub cab\y' THEN 'Club Cab'
      WHEN txt ~* '\yxtra ?cab\y' THEN 'XtraCab'
      WHEN txt ~* '\y(?:regular|reg|single|standard) cab\y' THEN 'Regular Cab'
      WHEN txt ~* '\yday cab\y' THEN 'Day Cab'
      ELSE '' END
  );
END;
$$;

ALTER TABLE vehicle_templates ADD COLUMN IF NOT EXISTS facet_wheelbase TEXT
  GENERATED ALWAYS AS (vehicle_template_facets(variant, name, wheelbase_in) ->> 'wheelbase') STORED;
ALTER TABLE vehicle_templates ADD COLUMN IF NOT EXISTS facet_body TEXT
  GENERATED ALWAYS AS (vehicle_template_facets(variant, name, wheelbase_in) ->> 'body') STORED;
ALTER TABLE vehicle_templates ADD COLUMN IF NOT EXISTS facet_roof TEXT
  GENERATED ALWAYS AS (vehicle_template_facets(variant, name, wheelbase_in) ->> 'roof') STORED;
ALTER TABLE vehicle_templates ADD COLUMN IF NOT EXISTS facet_bed TEXT
  GENERATED ALWAYS AS (vehicle_template_facets(variant, name, wheelbase_in) ->> 'bed') STORED;
ALTER TABLE vehicle_templates ADD COLUMN IF NOT EXISTS facet_cab TEXT
  GENERATED ALWAYS AS (vehicle_template_facets(variant, name, wheelbase_in) ->> 'cab') STORED;

-- What the search box matches against: label + name + code, lowercased
-- (same haystack as the old in-browser search).
ALTER TABLE vehicle_templates ADD COLUMN IF NOT EXISTS search_text TEXT
  GENERATED ALWAYS AS (lower(
    COALESCE(year, '') || ' ' || make || ' ' || model || ' ' || COALESCE(variant, '') || ' ' ||
    name || ' ' || COALESCE(template_code, '')
  )) STORED;

-- The picker's order, over the rows it can show.
CREATE INDEX IF NOT EXISTS vehicle_templates_picker_idx
  ON vehicle_templates (make, model, id)
  WHERE template_image_path IS NOT NULL;

-- One picker filter: unset, or equal ignoring case and outer spaces.
CREATE OR REPLACE FUNCTION public.vehicle_template_filter_ok(p_filters JSONB, p_key TEXT, p_value TEXT)
RETURNS BOOLEAN
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT COALESCE(p_filters ->> p_key, '') = ''
      OR lower(btrim(COALESCE(p_value, ''))) = lower(btrim(p_filters ->> p_key));
$$;

-- Choices for each picker dropdown. Each dropdown's choices are what's left
-- after applying all the OTHER filters, so picking Ford + Transit leaves only
-- the wheelbases and roofs a Transit comes in. Values are deduped ignoring
-- case (the library holds "FORD" and "Ford"), keeping the most common
-- spelling. Retired templates are left out.
CREATE OR REPLACE FUNCTION public.vehicle_template_filter_options(p_filters JSONB DEFAULT '{}'::JSONB)
RETURNS JSONB
LANGUAGE sql
STABLE
AS $$
  WITH t AS (
    SELECT
      btrim(COALESCE(year, '')) AS year, btrim(make) AS make, btrim(model) AS model,
      COALESCE(facet_body, '') AS body, COALESCE(facet_wheelbase, '') AS wheelbase,
      COALESCE(facet_roof, '') AS roof, COALESCE(facet_bed, '') AS bed, COALESCE(facet_cab, '') AS cab
    FROM vehicle_templates
    WHERE template_image_path IS NOT NULL AND is_active IS DISTINCT FROM false
  ),
  f AS (
    SELECT t.*,
      vehicle_template_filter_ok(p_filters, 'year', year) AS ok_year,
      vehicle_template_filter_ok(p_filters, 'make', make) AS ok_make,
      vehicle_template_filter_ok(p_filters, 'model', model) AS ok_model,
      vehicle_template_filter_ok(p_filters, 'body', body) AS ok_body,
      vehicle_template_filter_ok(p_filters, 'wheelbase', wheelbase) AS ok_wheelbase,
      vehicle_template_filter_ok(p_filters, 'roof', roof) AS ok_roof,
      vehicle_template_filter_ok(p_filters, 'bed', bed) AS ok_bed,
      vehicle_template_filter_ok(p_filters, 'cab', cab) AS ok_cab
    FROM t
  ),
  kv AS (
    SELECT 'year' AS k, year AS v FROM f WHERE ok_make AND ok_model AND ok_body AND ok_wheelbase AND ok_roof AND ok_bed AND ok_cab
    UNION ALL SELECT 'make', make FROM f WHERE ok_year AND ok_model AND ok_body AND ok_wheelbase AND ok_roof AND ok_bed AND ok_cab
    UNION ALL SELECT 'model', model FROM f WHERE ok_year AND ok_make AND ok_body AND ok_wheelbase AND ok_roof AND ok_bed AND ok_cab
    UNION ALL SELECT 'body', body FROM f WHERE ok_year AND ok_make AND ok_model AND ok_wheelbase AND ok_roof AND ok_bed AND ok_cab
    UNION ALL SELECT 'wheelbase', wheelbase FROM f WHERE ok_year AND ok_make AND ok_model AND ok_body AND ok_roof AND ok_bed AND ok_cab
    UNION ALL SELECT 'roof', roof FROM f WHERE ok_year AND ok_make AND ok_model AND ok_body AND ok_wheelbase AND ok_bed AND ok_cab
    UNION ALL SELECT 'bed', bed FROM f WHERE ok_year AND ok_make AND ok_model AND ok_body AND ok_wheelbase AND ok_roof AND ok_cab
    UNION ALL SELECT 'cab', cab FROM f WHERE ok_year AND ok_make AND ok_model AND ok_body AND ok_wheelbase AND ok_roof AND ok_bed
  ),
  deduped AS (
    SELECT k, mode() WITHIN GROUP (ORDER BY v) AS v
    FROM kv
    WHERE v <> ''
    GROUP BY k, lower(v)
  )
  SELECT jsonb_build_object(
    'year', '[]'::JSONB, 'make', '[]'::JSONB, 'model', '[]'::JSONB, 'body', '[]'::JSONB,
    'wheelbase', '[]'::JSONB, 'roof', '[]'::JSONB, 'bed', '[]'::JSONB, 'cab', '[]'::JSONB
  ) || COALESCE((
    SELECT jsonb_object_agg(k, vals)
    FROM (SELECT k, jsonb_agg(v ORDER BY v) AS vals FROM deduped GROUP BY k) g
  ), '{}'::JSONB);
$$;

-- Search + filter the library, a page at a time. Every space-separated term
-- of p_query must appear somewhere in search_text ("transit 2023 high" finds
-- 2023 High Roof Transits in any word order). Returns the page of rows, the
-- total with the filters, and the total without them (so the picker can say
-- "N more without the filters").
CREATE OR REPLACE FUNCTION public.search_vehicle_templates(
  p_query TEXT DEFAULT '',
  p_filters JSONB DEFAULT '{}'::JSONB,
  p_limit INTEGER DEFAULT 50,
  p_offset INTEGER DEFAULT 0,
  p_include_retired BOOLEAN DEFAULT false
)
RETURNS JSONB
LANGUAGE sql
STABLE
AS $$
  WITH terms AS (
    SELECT array_remove(regexp_split_to_array(lower(btrim(COALESCE(p_query, ''))), '\s+'), '') AS a
  ),
  matched AS (
    SELECT vt.*
    FROM vehicle_templates vt, terms
    WHERE vt.template_image_path IS NOT NULL
      AND (p_include_retired OR vt.is_active IS DISTINCT FROM false)
      AND NOT EXISTS (SELECT 1 FROM unnest(terms.a) AS term WHERE strpos(vt.search_text, term) = 0)
  ),
  filtered AS (
    SELECT * FROM matched m
    WHERE vehicle_template_filter_ok(p_filters, 'year', m.year)
      AND vehicle_template_filter_ok(p_filters, 'make', m.make)
      AND vehicle_template_filter_ok(p_filters, 'model', m.model)
      AND vehicle_template_filter_ok(p_filters, 'body', m.facet_body)
      AND vehicle_template_filter_ok(p_filters, 'wheelbase', m.facet_wheelbase)
      AND vehicle_template_filter_ok(p_filters, 'roof', m.facet_roof)
      AND vehicle_template_filter_ok(p_filters, 'bed', m.facet_bed)
      AND vehicle_template_filter_ok(p_filters, 'cab', m.facet_cab)
  ),
  page AS (
    SELECT id, name, make, model, year, variant, scale, template_code, template_image_path,
      px_per_in, overall_length_in, overall_height_in, wheelbase_in, panel_data, is_active,
      facet_wheelbase, facet_body, facet_roof, facet_bed, facet_cab
    FROM filtered
    ORDER BY make, model, id
    LIMIT GREATEST(COALESCE(p_limit, 50), 0) OFFSET GREATEST(COALESCE(p_offset, 0), 0)
  )
  SELECT jsonb_build_object(
    'total', (SELECT count(*) FROM filtered),
    'unfiltered_total', (SELECT count(*) FROM matched),
    'rows', COALESCE((SELECT jsonb_agg(to_jsonb(p) ORDER BY p.make, p.model, p.id) FROM page p), '[]'::JSONB)
  );
$$;

-- Library counts for the Templates tab label and the calibration banner.
CREATE OR REPLACE FUNCTION public.vehicle_template_stats()
RETURNS JSONB
LANGUAGE sql
STABLE
AS $$
  SELECT jsonb_build_object(
    'total', count(*),
    'active', count(*) FILTER (WHERE is_active IS DISTINCT FROM false),
    'uncalibrated', count(*) FILTER (WHERE COALESCE(px_per_in, 0) = 0)
  )
  FROM vehicle_templates
  WHERE template_image_path IS NOT NULL;
$$;

-- The page calls these through the API right after the deploy.
NOTIFY pgrst, 'reload schema';
